WHEEL_DIAMETER = 62.4
AXLE_TRACK = 128


DEFAULT_SPEED_PERCENTAGE = 75
DEFAULT_ACCELERATION_PERCENTAGE = 75
DEFAULT_TURN_RATE_PERCENTAGE = 50
DEFAULT_TURN_ACCELERATION_PERCENTAGE = 50


# SPEED = 216
# ACCELERATION = 811
# TURN_RATE = 184
# TURN_ACCELERATION = 830
